# Generated by Django 5.2.9 on 2025-12-30 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Field Template',
                'verbose_name_plural': 'Field Templates',
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consignment',
                'verbose_name_plural': 'Consignments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='consignment_name_7361bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field_name', models.CharField(blank=True, max_length=200)),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='consignment.consignment')),
                ('field_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='consignment.fieldtemplate')),
            ],
            options={
                'verbose_name': 'Consignment Measurement',
                'verbose_name_plural': 'Consignment Measurements',
                'unique_together': {('consignment', 'field_template', 'custom_field_name')},
            },
        ),
    ]
