# Generated by Django 5.2.9 on 2026-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtemplate',
            options={'ordering': ['order', 'field_name'], 'verbose_name': 'Field Template', 'verbose_name_plural': 'Field Templates'},
        ),
        migrations.AddField(
            model_name='fieldtemplate',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
